title: Aysegul Turk # your name (or website title) here
logo: "/images/at.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data scientist with 4+ years of analytics and consulting experience in automotive and energy industries. Previously worked at Uni-Select, Shell, Ford Motor Company of Australia and Deloitte.   
  <br><br>
  BSC in Industrial Engineering, Operations Research
 
  PostGraduate Diploma in Business Analytics 
  <br><br>
  <a href="https://www.linkedin.com/in/aysegulturk">View My LinkedIn Profile</a> 

  
